# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftranslate.proto\x12\ttranslate\"\x14\n\x04Link\x12\x0c\n\x04link\x18\x01 \x01(\t\"\x1c\n\x08\x46ilename\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2L\n\x0bVoTranslate\x12=\n\x13\x44ownloadTranslation\x12\x0f.translate.Link\x1a\x13.translate.Filename\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LINK']._serialized_start=30
  _globals['_LINK']._serialized_end=50
  _globals['_FILENAME']._serialized_start=52
  _globals['_FILENAME']._serialized_end=80
  _globals['_VOTRANSLATE']._serialized_start=82
  _globals['_VOTRANSLATE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
